image: spiriitlabs/symfony-cli:8.2-minimalist

stages:
  - dependencies
  - test-cs
  - test

.common-needs: &common-needs
  needs:
    - job: composer
      artifacts: true

composer:
  stage: dependencies
  script:
    - symfony composer install
  artifacts:
    expire_in: 1 hour
    paths:
      - vendor

php-cs-fix:
  <<: *common-needs
  stage: test-cs
  script:
    - vendor/bin/php-cs-fixer fix --verbose --allow-risky=yes --config .php-cs-fixer.php

php-stan:
  <<: *common-needs
  stage: test-cs
  script:
    - symfony php vendor/bin/phpstan analyse

test-7.4:
  <<: *common-needs
  image: spiriitlabs/symfony-cli:7.4-minimalist
  stage: test
  script:
    - echo '7.4' > .php-version
    - symfony composer update
    - symfony php vendor/bin/phpunit

test-8.1:
  <<: *common-needs
  image: spiriitlabs/symfony-cli:8.1-minimalist
  stage: test
  script:
    - echo '8.1' > .php-version
    - symfony composer update
    - symfony php vendor/bin/phpunit

test-8.2:
  <<: *common-needs
  stage: test
  script:
    - echo '8.2' > .php-version
    - symfony composer update
    - symfony php vendor/bin/phpunit

