image: php:latest

cache:
  paths:
    - vendor/

before_script:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq git libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libonig-dev libzip-dev
  - sudo docker-php-ext-install mbstring pdo_pgsql curl intl gd xml zip bz2 opcache
  - sudo pecl install xdebug
  - sudo docker-php-ext-enable xdebug
  - sudo curl -sS https://getcomposer.org/installer | php
  - sudo php composer.phar install

code-stander-test:
  stage: test
  script:
    - vendor/bin/php-cs-fixer fix --verbose --allow-risky=yes --config .php-cs-fixer.php
    - php vendor/bin/phpstan analyse

test-7.4:
  stage: test
  script:
    - echo '7.4' > .php-version
    - composer update
    - symfony php vendor/bin/phpunit

test-8.1:
  stage: test
  script:
    - echo '8.1' > .php-version
    - composer update
    - symfony php vendor/bin/phpunit

test-8.2:
  stage: test
  script:
    - echo '8.2' > .php-version
    - composer update
    - symfony php vendor/bin/phpunit

